# Кандидатогенерация для поиска услуг Авито

**Самостоятельный ноутбук:** для запуска нужны только этот `.ipynb` и три
исходных Parquet-файла. Весь код обработки, обучения, оценки и инференса
находится ниже. Папка `src`, Python-скрипты и готовая модель не нужны.

Положите данные в `datasets/` рядом с ноутбуком (либо измените `DATA_DIR`),
выберите Python 3.12 и выполните **Restart Kernel → Run All**. В Colab можно
использовать CPU; GPU для этой версии не нужен. На выходе получатся `answer.csv`,
сохранённая модель и отчёты в `notebook_outputs/`.

Цель — вернуть 50 уникальных объявлений на запрос. Метрика — средний по
запросам Recall@50. Начинаем с быстрого локального поиска: BM25, символьный
TF-IDF и мягкие признаки географии и подкатегории.

## 1. Окружение и настройки

Ячейка ниже устанавливает зависимости только при отсутствии нужной библиотеки.
Для точного повторения версий можно включить `INSTALL_EXACT_VERSIONS` и после
установки перезапустить ядро. Установка пакетов может обращаться к PyPI;
дальнейшие обучение и поиск работают полностью локально.

In [1]:
import importlib.util
import importlib.metadata
import subprocess
import sys

INSTALL_EXACT_VERSIONS = False
PACKAGES = {
    'numpy': ('numpy', '2.5.3'),
    'scipy': ('scipy', '1.18.1'),
    'pandas': ('pandas', '3.0.6'),
    'pyarrow': ('pyarrow', '25.0.1'),
    'sklearn': ('scikit-learn', '1.9.1'),
    'nltk': ('nltk', '3.10.3'),
    'tqdm': ('tqdm', '4.70.1'),
    'cloudpickle': ('cloudpickle', '3.1.2'),
}
missing = [name for name in PACKAGES if importlib.util.find_spec(name) is None]
if missing or INSTALL_EXACT_VERSIONS:
    requirements = [f'{package}=={version}' for package, version in PACKAGES.values()]
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', *requirements])
print('Python:', sys.version.split()[0])
print({package: importlib.metadata.version(package) for package, _ in PACKAGES.values()})

Python: 3.12.13
{'numpy': '2.5.3', 'scipy': '1.18.1', 'pandas': '3.0.6', 'pyarrow': '25.0.1', 'scikit-learn': '1.9.1', 'nltk': '3.10.3', 'tqdm': '4.70.1', 'cloudpickle': '3.1.2'}

In [2]:
from pathlib import Path
import gc
import gzip
import hashlib
import json
import logging
import time

import cloudpickle
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from IPython.display import display

DATA_DIR = Path('datasets')
OUTPUT_DIR = Path('.')
SEED = 2026
VALIDATION_QUERIES = 1200

EXPECTED_FILES = ['train.parquet', 'benchmark_queries.parquet', 'benchmark_items.parquet']
if not DATA_DIR.exists() and all(Path(name).exists() for name in EXPECTED_FILES):
    DATA_DIR = Path('.')
for name in EXPECTED_FILES:
    assert (DATA_DIR / name).is_file(), f'Не найден {DATA_DIR / name}; проверь DATA_DIR'

REPORT_DIR = OUTPUT_DIR / 'notebook_outputs'
REPORT_DIR.mkdir(parents=True, exist_ok=True)
MODEL_PATH = REPORT_DIR / 'model.pkl.gz'
ANSWER_PATH = OUTPUT_DIR / 'answer.csv'
previous_answer_hash = hashlib.sha256(ANSWER_PATH.read_bytes()).hexdigest() if ANSWER_PATH.exists() else None
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
QUERY_COLUMNS = ['search_query', 'search_location_id', 'search_is_delivery_search',
                 'search_infm_params_text', 'search_category']
started = time.perf_counter()

## 2. Обработка текста и чтение данных

Идентификаторы сохраняем строками. Нормализуем только тексты: регистр, `ё/е`,
HTML, пунктуацию. Стемминг Snowball объединяет часть русских словоформ;
скачивание словарей не требуется. Кэш ускоряет обработку повторяющихся слов.

В train есть только положительные пары. Запрос определяем по всем пяти
`search_*` полям: одинаковый текст в другом городе или с другими фильтрами
может иметь другой набор позитивов.

In [3]:
"""Обработка русского текста без загрузки словарей или внешних сервисов."""

import html
import re

from nltk.stem.snowball import RussianStemmer

_STEMMER = RussianStemmer()
_WORDS = re.compile(r"[a-zа-я0-9]+")
_HTML = re.compile(r"<[^>]+>")
_STOP = set("и в во на по для с со из от до за к ко у о об а но или это как мы вы я он она они наш ваш при без под над не что же ли бы все еще уже так то же".split())


def normalize(text: str) -> str:
    """Осторожная нормализация; идентификаторы через эту функцию не проходят."""
    text = html.unescape(str(text or "")).lower().replace("ё", "е")
    return " ".join(_WORDS.findall(_HTML.sub(" ", text)))


# Обычный словарь сохраняется вместе с функцией через cloudpickle.
# В отличие от lru_cache, он не требует определения stem в новом процессе.
_STEM_CACHE = {}


def stem(word: str) -> str:
    if word not in _STEM_CACHE:
        result = _STEMMER.stem(word)
        if len(_STEM_CACHE) < 300_000:
            _STEM_CACHE[word] = result
        return result
    return _STEM_CACHE[word]


def tokenize(text: str) -> list[str]:
    return [stem(w) for w in normalize(text).split() if len(w) > 1 and w not in _STOP]

In [4]:
"""Загрузка данных и разделение по текстам запросов без утечки позитивов."""

from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq


TRAIN_COLUMNS = QUERY_COLUMNS + ["item_id", "item_microcat_id", "item_location_id",
                                  "item_latitude", "item_longitude"]


def read_parquet(path, columns=None, filters=None):
    table = pq.read_table(path, columns=columns, filters=filters)
    # Decimal нужен исходному хранилищу, но для координат/цены достаточно float64.
    for i, field in enumerate(table.schema):
        if pa.types.is_decimal(field.type):
            table = table.set_column(i, field.name, table.column(i).cast(pa.float64()))
    return table.to_pandas()


def validation_split(train, n_queries=1200, seed=2026):
    normalized = train.search_query.map(normalize)
    texts = np.array(sorted(normalized.unique()))
    if n_queries >= len(texts):
        raise ValueError("Для обучения должны остаться тексты запросов")
    rng = np.random.default_rng(seed)
    chosen = rng.choice(texts, size=n_queries, replace=False)
    heldout = train.loc[normalized.isin(chosen)]
    contexts = heldout[QUERY_COLUMNS].drop_duplicates().copy()
    contexts["normalized_query"] = contexts.search_query.map(normalize)
    contexts["random_order"] = rng.random(len(contexts))
    # Одна комбинация контекста на текст: иначе частые формулировки подавят редкие.
    selected = contexts.sort_values("random_order").drop_duplicates("normalized_query")
    selected = selected.sort_values("normalized_query").reset_index(drop=True)
    labels = heldout.groupby(QUERY_COLUMNS, dropna=False).item_id.agg(lambda ids: sorted(set(ids)))
    selected["relevant_ids"] = [labels.loc[tuple(row)] for row in selected[QUERY_COLUMNS].itertuples(index=False, name=None)]
    order = rng.permutation(len(selected))
    selected["split"] = "holdout"
    selected.loc[order[:int(len(selected) * 2 / 3)], "split"] = "dev"
    selected["query_id"] = [f"validation_{i:05d}" for i in range(len(selected))]
    selected = selected.drop(columns="random_order")
    fitting = train.loc[~normalized.isin(chosen)].copy()
    assert not set(fitting.search_query.map(normalize)) & set(selected.normalized_query)
    return fitting, selected


def load_training_problem(data_dir: Path, n_queries=1200, seed=2026):
    train = read_parquet(data_dir / "train.parquet", columns=TRAIN_COLUMNS)
    corpus = read_parquet(data_dir / "benchmark_items.parquet")
    queries = read_parquet(data_dir / "benchmark_queries.parquet")
    fitting, validation = validation_split(train, n_queries=n_queries, seed=seed)
    relevant_ids = set(i for ids in validation.relevant_ids for i in ids)
    absent = sorted(relevant_ids - set(corpus.item_id))
    extra = read_parquet(data_dir / "train.parquet", columns=list(corpus.columns),
                         filters=[("item_id", "in", absent)]) if absent else corpus.iloc[:0]
    # Если объявление уже есть в benchmark, его версию считаем канонической.
    index_items = pd.concat([corpus, extra], ignore_index=True).drop_duplicates("item_id")
    assert relevant_ids <= set(index_items.item_id)
    return train, fitting, validation, corpus, index_items, queries

In [5]:
files = []
for name in EXPECTED_FILES:
    path = DATA_DIR / name
    parquet = pq.ParquetFile(path)
    files.append({'file': name, 'rows': parquet.metadata.num_rows,
                  'columns': len(parquet.schema_arrow),
                  'MiB': round(path.stat().st_size / 2**20, 1)})
display(pd.DataFrame(files))

train, fitting, validation, corpus, index_items, queries = load_training_problem(
    DATA_DIR, n_queries=VALIDATION_QUERIES, seed=SEED)

eda = {
    'Уникальные контексты train': len(train[QUERY_COLUMNS].drop_duplicates()),
    'Уникальные нормализованные тексты train': train.search_query.map(normalize).nunique(),
    'Повторные пары контекст–объявление': int(train.duplicated(QUERY_COLUMNS + ['item_id']).sum()),
    'Доля пар с разными локациями': float((train.search_location_id != train.item_location_id).mean()),
    'Доля train-строк с item_id в benchmark': float(train.item_id.isin(corpus.item_id).mean()),
}
display(pd.Series(eda, name='value').to_frame())

                        file    rows  columns    MiB
0              train.parquet  497673       19  467.5
1  benchmark_queries.parquet    2452        6    0.1
2    benchmark_items.parquet  189212       14  186.6

                                                 value
Уникальные контексты train               354463.000000
Уникальные нормализованные тексты train   73706.000000
Повторные пары контекст–объявление        30619.000000
Доля пар с разными локациями                  0.168980
Доля train-строк с item_id в benchmark        0.066329

## 3. Валидация

Разделение выполнено **по нормализованным текстам**: все пары с отложенными
формулировками удалены из обучения статистик. На каждый текст берём один
случайный контекст и все известные позитивы этого контекста. Повторы
позитивных `item_id` удаляем.

Из 1 200 запросов 800 используются для выбора конфигурации, 400 — только
для итоговой проверки. Все позитивные объявления должны присутствовать
в поисковом корпусе. Поэтому к benchmark добавлены недостающие документы
из train. Индекс видит их тексты, но не validation-связи запрос–объявление.

**Локальная оценка не равна метрике скрытого бенчмарка.** Состав конкурирующих
объявлений и распределение текстов отличаются; это может делать оценку
оптимистичной. Bootstrap-интервал ниже не учитывает этот сдвиг.

In [6]:
assert not set(fitting.search_query.map(normalize)) & set(validation.normalized_query)
assert validation.normalized_query.nunique() == len(validation)
assert set(i for ids in validation.relevant_ids for i in ids) <= set(index_items.item_id)
display(validation.groupby('split').agg(queries=('query_id', 'size')))
print('Документов в корпусе валидации:', len(index_items))
print('Пар для обучения статистик:', len(fitting))
validation.to_parquet(REPORT_DIR / 'validation_queries.parquet', index=False)

         queries
split
dev          800
holdout      400

Документов в корпусе валидации: 190392
Пар для обучения статистик: 489371

## 4. Поиск кандидатов

В следующих двух ячейках находится **полная реализация** алгоритма.

* BM25 отдельно по заголовку и по заголовку + параметрам + описанию.
  Параметры обрезаются до 1 800 символов, описание — до 5 000.
* Символьные n-граммы 3–5 по заголовкам помогают сопоставлять словоформы
  и похожие написания. Сходство — косинусное по TF-IDF.
* География учитывается мягко: совпадение локации, близость координат
  и переходы между поисковой локацией и локацией объявления из train.
* Для прогноза подкатегории используем 20 похожих train-запросов и
  распределения выбранных ими `item_microcat_id`, с весами similarity^6.
* Рейтинг и число отзывов дают небольшую добавку качества.

`score = text_score * (1 + w_geo * geo) * (1 + w_category * category) + w_quality * quality`

Жёстких географических исключений нет. При равных оценках используем порядок
по `item_id`, чтобы top-50 воспроизводился. Не используем ручные ответы
или правила под конкретные benchmark `query_id`.

In [7]:
"""Разреженный текстовый поиск и мягкие признаки контекста.

BM25 вычисляется как произведение разреженных матриц: вся коллекция
не обходится Python-циклом для каждого запроса. Все обучаемые статистики
сосредоточены в fit_history(), чтобы явно исключать validation из обучения.
"""

from dataclasses import asdict, dataclass
import logging

import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import normalize as l2_normalize
from tqdm.auto import tqdm


LOG = logging.getLogger(__name__)
QUERY_COLUMNS = ["search_query", "search_location_id", "search_is_delivery_search",
                 "search_infm_params_text", "search_category"]
FEATURES = ["title", "body", "char", "filters", "geo", "microcat", "quality"]


@dataclass
class SearchConfig:
    title: float = 1.5
    body: float = 1.0
    char: float = 1.0
    filters: float = 0.15
    geo: float = 3.0
    microcat: float = 0.5
    quality: float = 0.05

    def as_dict(self):
        return asdict(self)


def topk(scores: np.ndarray, k: int) -> np.ndarray:
    """Детерминированный top-k: при равных оценках меньший индекс раньше.

    Документы заранее сортируются по item_id. Учитываем также равенство
    оценок на границе top-k, которое один argpartition не разрешает стабильно.
    """
    k = min(k, len(scores))
    if k == 0:
        return np.empty(0, dtype=np.int32)
    cutoff = np.partition(scores, len(scores) - k)[len(scores) - k]
    above = np.flatnonzero(scores > cutoff)
    tied = np.flatnonzero(scores == cutoff)[:k - len(above)]
    selected = np.concatenate([above, tied])
    return selected[np.lexsort((selected, -scores[selected]))].astype(np.int32)


class BM25Field:
    def __init__(self, max_features=250_000, k1=1.2, b=0.65):
        self.k1, self.b = k1, b
        self.vectorizer = CountVectorizer(
            tokenizer=tokenize, token_pattern=None, lowercase=False,
            min_df=2, max_features=max_features, dtype=np.float32,
        )

    def fit(self, documents):
        counts = self.vectorizer.fit_transform(documents).tocsr()
        n = counts.shape[0]
        lengths = np.asarray(counts.sum(axis=1)).ravel()
        df = np.bincount(counts.indices, minlength=counts.shape[1])
        self.idf = np.log1p((n - df + 0.5) / (df + 0.5)).astype(np.float32)
        norm = self.k1 * (1 - self.b + self.b * lengths / max(lengths.mean(), 1))
        denominator = counts.data + np.repeat(norm, np.diff(counts.indptr))
        counts.data = (counts.data * (self.k1 + 1) / denominator
                       * self.idf[counts.indices]).astype(np.float32)
        self.postings = counts.T.tocsr()
        return self

    def transform_queries(self, texts):
        q = self.vectorizer.transform(texts).tocsr()
        q.data[:] = 1  # Повтор слова в запросе не усиливает его искусственно.
        denominator = np.asarray(q @ self.idf).ravel() * (self.k1 + 1)
        return q, np.maximum(denominator, 1e-6)

    def score(self, row, denominator):
        return (row @ self.postings).toarray().ravel() / denominator

    def restrict(self, indices):
        self.postings = self.postings[:, indices].tocsr()

/Users/strafe/VSCode-Projects/DataScience-Bootcamp2026/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
class CandidateModel:
    def fit_index(self, items: pd.DataFrame):
        """Индекс использует только тексты и метаданные документов, не метки."""
        items = items.drop_duplicates("item_id").sort_values("item_id").reset_index(drop=True)
        self.item_ids = items.item_id.to_numpy(dtype=str)
        self.locations = items.item_location_id.fillna(-1).to_numpy(np.int64)
        self.microcats = items.item_microcat_id.fillna(-1).to_numpy(np.int64)
        self.latitudes = pd.to_numeric(items.item_latitude, errors="coerce").to_numpy(float)
        self.longitudes = pd.to_numeric(items.item_longitude, errors="coerce").to_numpy(float)
        reviews = items.item_rating_reviews_count.fillna(0).to_numpy(np.float32)
        ratings = items.item_rating.fillna(0).to_numpy(np.float32)
        self.quality = (0.75 * np.minimum(np.log1p(np.maximum(reviews, 0)) / 7, 1)
                        + 0.25 * np.clip(ratings / 5, 0, 1)).astype(np.float32)
        titles = items.item_title_raw.fillna("").tolist()
        bodies = (items.item_title_raw.fillna("") + " "
                  + items.item_infm_params_text.fillna("").str.slice(0, 1800) + " "
                  + items.item_description_raw.fillna("").str.slice(0, 5000)).tolist()
        LOG.info("BM25: заголовки, %s документов", len(items))
        self.title_index = BM25Field(max_features=100_000, b=0.35).fit(titles)
        LOG.info("BM25: описание и параметры")
        self.body_index = BM25Field().fit(bodies)
        LOG.info("TF-IDF: символьные n-граммы заголовков")
        self.char_vectorizer = TfidfVectorizer(
            preprocessor=normalize, analyzer="char_wb", ngram_range=(3, 5),
            min_df=2, max_features=180_000, sublinear_tf=True, dtype=np.float32,
        )
        self.char_postings = self.char_vectorizer.fit_transform(titles).T.tocsr()
        self.config = SearchConfig()
        return self

    def fit_history(self, train: pd.DataFrame, location_metadata: pd.DataFrame):
        """Обучение географических переходов и kNN-классификатора подкатегории.

        В kNN хранятся текст запроса и распределение подкатегорий выбранных
        объявлений. Связи с query_id бенчмарка нигде не используются.
        """
        LOG.info("Статистики контекста: %s обучающих пар", len(train))
        unique = train.drop_duplicates(QUERY_COLUMNS + ["item_id"])
        geo = unique.groupby(["search_location_id", "item_location_id"]).size()
        self.geo_routes = {}
        for search_loc, group in geo.groupby(level=0):
            counts = group.droplevel(0)
            # Мягкая поправка помогает при поиске по региону/соседнему городу.
            affinity = np.sqrt(counts / counts.max())
            self.geo_routes[int(search_loc)] = affinity.to_dict()
        coords = location_metadata[["item_location_id", "item_latitude", "item_longitude"]].copy()
        for c in ["item_latitude", "item_longitude"]:
            coords[c] = pd.to_numeric(coords[c], errors="coerce")
        coords = coords.dropna().drop_duplicates()
        coords = coords[(coords.item_latitude.between(-90, 90))
                        & coords.item_longitude.between(-180, 180)]
        centers = coords.groupby("item_location_id")[["item_latitude", "item_longitude"]].median()
        self.location_centers = {int(k): tuple(v) for k, v in zip(centers.index, centers.to_numpy())}

        qdata = unique[["search_query", "item_microcat_id"]].copy()
        qdata["normalized"] = qdata.search_query.map(normalize)
        grouped = qdata.groupby(["normalized", "item_microcat_id"]).size().reset_index(name="count")
        self.history_texts = np.array(sorted(grouped.normalized.unique()), dtype=str)
        self.category_values = np.array(sorted(grouped.item_microcat_id.unique()), dtype=np.int64)
        qr = pd.Index(self.history_texts).get_indexer(grouped.normalized)
        cr = pd.Index(self.category_values).get_indexer(grouped.item_microcat_id)
        label_matrix = sparse.csr_matrix(
            (grouped["count"].to_numpy(np.float32), (qr, cr)),
            shape=(len(self.history_texts), len(self.category_values)),
        )
        self.history_labels = l2_normalize(label_matrix, norm="l1", axis=1)
        self.history_vectorizer = TfidfVectorizer(
            analyzer="char_wb", ngram_range=(3, 5), min_df=2,
            max_features=100_000, sublinear_tf=True, dtype=np.float32,
        )
        self.history_postings = self.history_vectorizer.fit_transform(self.history_texts).T.tocsr()
        self.item_category_indices = pd.Index(self.category_values).get_indexer(self.microcats)
        return self

    def geo_scores(self, location):
        same = (self.locations == location).astype(np.float32)
        scores = same.copy()
        center = self.location_centers.get(int(location))
        if center is not None:
            lat1, lon1 = np.radians(center)
            lat2, lon2 = np.radians(self.latitudes), np.radians(self.longitudes)
            a = np.sin((lat2-lat1)/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin((lon2-lon1)/2)**2
            distance = 6371.0088 * 2 * np.arcsin(np.sqrt(np.clip(a, 0, 1)))
            near = np.nan_to_num(np.exp(-distance / 40), nan=0).astype(np.float32)
            scores = np.maximum(scores, 0.7 * near)
        routes = self.geo_routes.get(int(location), {})
        if routes:
            locations, inverse = np.unique(self.locations, return_inverse=True)
            affinity = np.array([routes.get(int(loc), 0) for loc in locations], dtype=np.float32)
            scores = np.maximum(scores, 0.65 * affinity[inverse])
        return scores

    def category_scores(self, query_vector):
        similarities = (query_vector @ self.history_postings).toarray().ravel()
        neighbors = topk(similarities, 20)
        weights = similarities[neighbors] ** 6
        probs = np.asarray(self.history_labels[neighbors].T @ weights).ravel()
        if probs.max(initial=0) > 0:
            probs /= probs.max()
        scores = np.zeros(len(self.item_ids), dtype=np.float32)
        known = self.item_category_indices >= 0
        scores[known] = probs[self.item_category_indices[known]]
        return scores

    @staticmethod
    def combine(features, config):
        text = (config.title * features[:, 0] + config.body * features[:, 1]
                + config.char * features[:, 2] + config.filters * features[:, 3])
        # География/категория усиливают текстовое совпадение, но не отсекают
        # объявления и не могут полностью заменить совпадение текста.
        return (text * (1 + config.geo * features[:, 4])
                * (1 + config.microcat * features[:, 5])
                + config.quality * features[:, 6])

    def iter_features(self, queries, progress=True):
        texts = queries.search_query.fillna("").tolist()
        filters = queries.search_infm_params_text.fillna("").tolist()
        tq, td = self.title_index.transform_queries(texts)
        bq, bd = self.body_index.transform_queries(texts)
        fq, fd = self.body_index.transform_queries(filters)
        cq = self.char_vectorizer.transform(texts)
        hq = self.history_vectorizer.transform([normalize(t) for t in texts])
        # В кэше только локации текущего пакета запросов; после вызова он удаляется.
        geo_cache = {}
        for i, row in enumerate(tqdm(queries.itertuples(index=False), total=len(queries),
                                     disable=not progress, desc="Поиск")):
            loc = int(row.search_location_id)
            if loc not in geo_cache:
                if len(geo_cache) >= 32:
                    geo_cache.clear()
                geo_cache[loc] = self.geo_scores(loc)
            yield np.column_stack([
                self.title_index.score(tq[i], td[i]),
                self.body_index.score(bq[i], bd[i]),
                (cq[i] @ self.char_postings).toarray().ravel(),
                self.body_index.score(fq[i], fd[i]),
                geo_cache[loc], self.category_scores(hq[i]), self.quality,
            ]).astype(np.float32, copy=False)

    def predict(self, queries, k=50, progress=True):
        return [self.item_ids[topk(self.combine(f, self.config), k)].tolist()
                for f in self.iter_features(queries, progress=progress)]

    def restrict_items(self, allowed_ids):
        """Финальный индекс возвращает только документы разрешённого корпуса.

        Словарь/IDF сохраняются: они обучены на текстах benchmark и добавленных
        документах train, без использования validation-меток в скоринге.
        """
        keep = np.flatnonzero(np.isin(self.item_ids, list(allowed_ids)))
        for name in ["item_ids", "locations", "microcats", "latitudes", "longitudes", "quality",
                     "item_category_indices"]:
            setattr(self, name, getattr(self, name)[keep])
        self.title_index.restrict(keep)
        self.body_index.restrict(keep)
        self.char_postings = self.char_postings[:, keep].tocsr()
        return self

In [9]:
location_metadata = pd.concat([
    train[['item_location_id', 'item_latitude', 'item_longitude']],
    corpus[['item_location_id', 'item_latitude', 'item_longitude']],
])
# Здесь только метаданные документов; связи validation-запросов не используются.
model = CandidateModel().fit_index(index_items)
model.fit_history(fitting, location_metadata)
print('Индекс готов:', len(model.item_ids), 'документов')

2026-09-28 18:39:30,302 INFO BM25: заголовки, 190392 документов

2026-09-28 18:39:31,239 INFO BM25: описание и параметры

2026-09-28 18:39:59,380 INFO TF-IDF: символьные n-граммы заголовков

2026-09-28 18:40:02,560 INFO Статистики контекста: 489371 обучающих пар

Индекс готов: 190392 документов

## 5. Recall@50, выбор конфигурации и holdout

Для запроса считаем `число найденных позитивов / число всех известных позитивов`.
Затем усредняем по запросам, а не по строкам train. Конфигурацию выбираем
по dev; holdout не участвует в выборе параметров. Ниже сравниваем также
чистый BM25 и комбинацию текстовых каналов без географии.

In [10]:
"""Recall@50 с усреднением по запросам, dev-подбор и отдельный holdout."""

import logging

import numpy as np
import pandas as pd


LOG = logging.getLogger(__name__)


def configs_to_compare():
    configs = {
        "bm25": SearchConfig(char=0, filters=0, geo=0, microcat=0, quality=0),
        "text": SearchConfig(geo=0, microcat=0, quality=0),
    }
    for geo in [2.0, 5.0, 10.0]:
        for cat in [0.0, 0.7, 2.0]:
            configs[f"geo{geo:g}_cat{cat:g}"] = SearchConfig(geo=geo, microcat=cat)
    for char in [0.0, 2.0]:
        configs[f"char{char:g}"] = SearchConfig(char=char, geo=5.0, microcat=0.7)
    configs["no_quality"] = SearchConfig(geo=5, microcat=0.7, quality=0)
    configs["quality_high"] = SearchConfig(geo=5, microcat=0.7, quality=0.25)
    return configs


def evaluate_configs(model, queries, configs):
    item_lookup = pd.Index(model.item_ids)
    truth_indices = [item_lookup.get_indexer(ids) for ids in queries.relevant_ids]
    if any((x < 0).any() or len(x) == 0 for x in truth_indices):
        raise ValueError("Не все validation-позитивы присутствуют в поисковом индексе")
    recalls = {name: [] for name in configs}
    selected_results = {name: [] for name in configs}
    for truth, features in zip(truth_indices, model.iter_features(queries)):
        for name, config in configs.items():
            indices = topk(model.combine(features, config), 50)
            recalls[name].append(float(np.isin(truth, indices).sum() / len(truth)))
            selected_results[name].append(indices)
    return {k: np.array(v) for k, v in recalls.items()}, selected_results


def bootstrap_interval(values, seed=2026):
    rng = np.random.default_rng(seed)
    means = np.mean(rng.choice(values, size=(2000, len(values)), replace=True), axis=1)
    return np.quantile(means, [0.025, 0.975]).tolist()


def tune_and_evaluate(model, validation):
    configs = configs_to_compare()
    dev = validation[validation.split == "dev"].copy()
    holdout = validation[validation.split == "holdout"].copy()
    LOG.info("Подбор %s конфигураций на %s dev-запросах", len(configs), len(dev))
    dev_recalls, _ = evaluate_configs(model, dev, configs)
    scores = {name: float(values.mean()) for name, values in dev_recalls.items()}
    best_name = max(scores, key=scores.get)
    model.config = configs[best_name]
    LOG.info("Лучшая конфигурация %s, dev Recall@50=%.4f", best_name, scores[best_name])
    # Конфигурация фиксируется ДО чтения holdout-метрик.
    holdout_configs = {"bm25": configs["bm25"], "text": configs["text"], "selected": model.config}
    holdout_recalls, predictions = evaluate_configs(model, holdout, holdout_configs)
    metrics = {
        "metric": "macro Recall@50", "split": "grouped by normalized search_query",
        "dev_queries": len(dev), "holdout_queries": len(holdout),
        "validation_corpus_size": len(model.item_ids),
        "dev_scores": scores, "selected_config_name": best_name,
        "selected_config": model.config.as_dict(),
        "holdout_scores": {k: float(v.mean()) for k, v in holdout_recalls.items()},
        "holdout_selected_bootstrap_95pct": bootstrap_interval(holdout_recalls["selected"]),
        "note": "Local validation, not the hidden benchmark score. All held-out positives are in the corpus.",
    }
    details = holdout.copy()
    details["recall_at_50"] = holdout_recalls["selected"]
    details["predicted_ids"] = [model.item_ids[p].tolist() for p in predictions["selected"]]
    details["relevant_count"] = details.relevant_ids.map(len)
    return metrics, details

In [11]:
metrics, details = tune_and_evaluate(model, validation)
display(pd.Series(metrics['dev_scores'], name='dev Recall@50').sort_values(ascending=False).to_frame())
print('Выбранная конфигурация:', metrics['selected_config_name'])
display(pd.Series(metrics['selected_config'], name='weight').to_frame())
display(pd.Series(metrics['holdout_scores'], name='holdout Recall@50').to_frame())
print('Bootstrap 95%:', metrics['holdout_selected_bootstrap_95pct'])
(REPORT_DIR / 'metrics.json').write_text(json.dumps(metrics, ensure_ascii=False, indent=2))
details.to_parquet(REPORT_DIR / 'holdout_details.parquet', index=False)

2026-09-28 18:40:04,225 INFO Подбор 15 конфигураций на 800 dev-запросах

Поиск:   0%|          | 0/800 [00:00<?, ?it/s]

Поиск:   0%|          | 3/800 [00:00<00:30, 26.42it/s]

Поиск:   1%|          | 6/800 [00:00<00:28, 28.36it/s]

Поиск:   1%|          | 9/800 [00:00<00:27, 28.64it/s]

Поиск:   2%|▏         | 13/800 [00:00<00:26, 29.95it/s]

Поиск:   2%|▏         | 16/800 [00:00<00:26, 29.52it/s]

Поиск:   2%|▎         | 20/800 [00:00<00:26, 29.43it/s]

Поиск:   3%|▎         | 23/800 [00:00<00:26, 29.09it/s]

Поиск:   3%|▎         | 27/800 [00:00<00:25, 30.29it/s]

Поиск:   4%|▍         | 31/800 [00:01<00:25, 29.87it/s]

Поиск:   4%|▍         | 35/800 [00:01<00:25, 30.19it/s]

Поиск:   5%|▍         | 39/800 [00:01<00:25, 30.42it/s]

Поиск:   5%|▌         | 43/800 [00:01<00:24, 30.85it/s]

Поиск:   6%|▌         | 47/800 [00:01<00:25, 29.64it/s]

Поиск:   6%|▋         | 50/800 [00:01<00:25, 29.09it/s]

Поиск:   7%|▋         | 53/800 [00:01<00:25, 28.82it/s]

Поиск:   7%|▋         | 57/800 [00:01<00:24, 29.99it/s]

Поиск:   8%|▊         | 61/800 [00:02<00:24, 30.54it/s]

Поиск:   8%|▊         | 65/800 [00:02<00:24, 30.00it/s]

Поиск:   9%|▊         | 69/800 [00:02<00:25, 29.00it/s]

Поиск:   9%|▉         | 72/800 [00:02<00:25, 28.70it/s]

Поиск:   9%|▉         | 75/800 [00:02<00:25, 28.98it/s]

Поиск:  10%|▉         | 78/800 [00:02<00:24, 28.95it/s]

Поиск:  10%|█         | 82/800 [00:02<00:23, 29.92it/s]

Поиск:  11%|█         | 85/800 [00:02<00:24, 29.31it/s]

Поиск:  11%|█▏        | 90/800 [00:03<00:21, 32.57it/s]

Поиск:  12%|█▏        | 94/800 [00:03<00:22, 31.79it/s]

Поиск:  12%|█▏        | 98/800 [00:03<00:22, 31.58it/s]

Поиск:  13%|█▎        | 102/800 [00:03<00:22, 30.45it/s]

Поиск:  13%|█▎        | 106/800 [00:03<00:22, 30.84it/s]

Поиск:  14%|█▍        | 110/800 [00:03<00:22, 31.29it/s]

Поиск:  14%|█▍        | 114/800 [00:03<00:22, 30.90it/s]

Поиск:  15%|█▍        | 118/800 [00:03<00:21, 31.27it/s]

Поиск:  15%|█▌        | 122/800 [00:04<00:21, 31.12it/s]

Поиск:  16%|█▌        | 126/800 [00:04<00:22, 30.33it/s]

Поиск:  16%|█▋        | 130/800 [00:04<00:23, 28.95it/s]

Поиск:  17%|█▋        | 133/800 [00:04<00:23, 28.66it/s]

Поиск:  17%|█▋        | 137/800 [00:04<00:22, 29.71it/s]

Поиск:  18%|█▊        | 140/800 [00:04<00:22, 29.31it/s]

Поиск:  18%|█▊        | 144/800 [00:04<00:21, 29.85it/s]

Поиск:  18%|█▊        | 147/800 [00:04<00:22, 29.17it/s]

Поиск:  19%|█▉        | 150/800 [00:05<00:22, 28.51it/s]

Поиск:  19%|█▉        | 154/800 [00:05<00:22, 29.08it/s]

Поиск:  20%|█▉        | 157/800 [00:05<00:22, 28.31it/s]

Поиск:  20%|██        | 160/800 [00:05<00:22, 27.92it/s]

Поиск:  20%|██        | 163/800 [00:05<00:22, 27.71it/s]

Поиск:  21%|██        | 166/800 [00:05<00:22, 27.80it/s]

Поиск:  21%|██▏       | 170/800 [00:05<00:21, 29.49it/s]

Поиск:  22%|██▏       | 173/800 [00:05<00:21, 29.43it/s]

Поиск:  22%|██▏       | 176/800 [00:05<00:21, 29.22it/s]

Поиск:  22%|██▎       | 180/800 [00:06<00:20, 30.19it/s]

Поиск:  23%|██▎       | 184/800 [00:06<00:20, 30.30it/s]

Поиск:  24%|██▎       | 188/800 [00:06<00:21, 28.92it/s]

Поиск:  24%|██▍       | 191/800 [00:06<00:21, 28.73it/s]

Поиск:  24%|██▍       | 194/800 [00:06<00:21, 28.29it/s]

Поиск:  25%|██▍       | 197/800 [00:06<00:21, 28.28it/s]

Поиск:  25%|██▌       | 201/800 [00:06<00:20, 28.70it/s]

Поиск:  26%|██▌       | 204/800 [00:06<00:20, 28.91it/s]

Поиск:  26%|██▌       | 207/800 [00:06<00:20, 29.03it/s]

Поиск:  26%|██▋       | 211/800 [00:07<00:19, 29.80it/s]

Поиск:  27%|██▋       | 215/800 [00:07<00:19, 30.36it/s]

Поиск:  27%|██▋       | 219/800 [00:07<00:19, 30.15it/s]

Поиск:  28%|██▊       | 223/800 [00:07<00:19, 29.33it/s]

Поиск:  28%|██▊       | 226/800 [00:07<00:20, 28.67it/s]

Поиск:  29%|██▊       | 229/800 [00:07<00:19, 28.95it/s]

Поиск:  29%|██▉       | 232/800 [00:07<00:20, 28.13it/s]

Поиск:  29%|██▉       | 235/800 [00:07<00:20, 27.26it/s]

Поиск:  30%|██▉       | 238/800 [00:08<00:20, 26.87it/s]

Поиск:  30%|███       | 241/800 [00:08<00:20, 26.97it/s]

Поиск:  30%|███       | 244/800 [00:08<00:20, 27.63it/s]

Поиск:  31%|███       | 248/800 [00:08<00:19, 28.48it/s]

Поиск:  31%|███▏      | 251/800 [00:08<00:19, 28.63it/s]

Поиск:  32%|███▏      | 255/800 [00:08<00:18, 29.57it/s]

Поиск:  32%|███▏      | 258/800 [00:08<00:18, 29.22it/s]

Поиск:  33%|███▎      | 261/800 [00:08<00:18, 28.63it/s]

Поиск:  33%|███▎      | 265/800 [00:09<00:18, 29.71it/s]

Поиск:  34%|███▎      | 268/800 [00:09<00:18, 29.17it/s]

Поиск:  34%|███▍      | 271/800 [00:09<00:18, 28.62it/s]

Поиск:  34%|███▍      | 274/800 [00:09<00:18, 28.15it/s]

Поиск:  35%|███▍      | 277/800 [00:09<00:18, 27.93it/s]

Поиск:  35%|███▌      | 280/800 [00:09<00:18, 28.40it/s]

Поиск:  35%|███▌      | 283/800 [00:09<00:18, 27.80it/s]

Поиск:  36%|███▌      | 286/800 [00:09<00:18, 27.73it/s]

Поиск:  36%|███▋      | 290/800 [00:09<00:17, 29.09it/s]

Поиск:  37%|███▋      | 294/800 [00:10<00:16, 30.87it/s]

Поиск:  37%|███▋      | 298/800 [00:10<00:16, 30.36it/s]

Поиск:  38%|███▊      | 302/800 [00:10<00:16, 30.55it/s]

Поиск:  38%|███▊      | 306/800 [00:10<00:15, 31.13it/s]

Поиск:  39%|███▉      | 310/800 [00:10<00:14, 32.96it/s]

Поиск:  39%|███▉      | 314/800 [00:10<00:14, 32.62it/s]

Поиск:  40%|███▉      | 318/800 [00:10<00:15, 31.58it/s]

Поиск:  40%|████      | 322/800 [00:10<00:15, 31.40it/s]

Поиск:  41%|████      | 326/800 [00:11<00:15, 31.24it/s]

Поиск:  41%|████▏     | 330/800 [00:11<00:15, 30.11it/s]

Поиск:  42%|████▏     | 334/800 [00:11<00:15, 29.69it/s]

Поиск:  42%|████▏     | 337/800 [00:11<00:15, 29.72it/s]

Поиск:  43%|████▎     | 341/800 [00:11<00:14, 31.41it/s]

Поиск:  43%|████▎     | 345/800 [00:11<00:14, 31.08it/s]

Поиск:  44%|████▎     | 349/800 [00:11<00:14, 31.00it/s]

Поиск:  44%|████▍     | 353/800 [00:11<00:14, 30.10it/s]

Поиск:  45%|████▍     | 357/800 [00:12<00:14, 30.47it/s]

Поиск:  45%|████▌     | 361/800 [00:12<00:15, 29.13it/s]

Поиск:  46%|████▌     | 365/800 [00:12<00:14, 30.71it/s]

Поиск:  46%|████▌     | 369/800 [00:12<00:14, 30.41it/s]

Поиск:  47%|████▋     | 373/800 [00:12<00:14, 29.89it/s]

Поиск:  47%|████▋     | 377/800 [00:12<00:13, 30.55it/s]

Поиск:  48%|████▊     | 381/800 [00:12<00:13, 29.93it/s]

Поиск:  48%|████▊     | 385/800 [00:12<00:14, 29.45it/s]

Поиск:  49%|████▊     | 389/800 [00:13<00:13, 30.39it/s]

Поиск:  49%|████▉     | 393/800 [00:13<00:13, 30.63it/s]

Поиск:  50%|████▉     | 397/800 [00:13<00:13, 30.00it/s]

Поиск:  50%|█████     | 401/800 [00:13<00:13, 29.53it/s]

Поиск:  50%|█████     | 404/800 [00:13<00:13, 29.19it/s]

Поиск:  51%|█████     | 408/800 [00:13<00:12, 30.21it/s]

Поиск:  52%|█████▏    | 412/800 [00:13<00:13, 28.38it/s]

Поиск:  52%|█████▏    | 416/800 [00:14<00:13, 29.32it/s]

Поиск:  52%|█████▏    | 419/800 [00:14<00:13, 28.77it/s]

Поиск:  53%|█████▎    | 423/800 [00:14<00:12, 29.43it/s]

Поиск:  53%|█████▎    | 427/800 [00:14<00:12, 29.56it/s]

Поиск:  54%|█████▍    | 430/800 [00:14<00:12, 29.20it/s]

Поиск:  54%|█████▍    | 434/800 [00:14<00:12, 30.16it/s]

Поиск:  55%|█████▍    | 438/800 [00:14<00:11, 30.21it/s]

Поиск:  55%|█████▌    | 442/800 [00:14<00:11, 29.98it/s]

Поиск:  56%|█████▌    | 445/800 [00:15<00:12, 29.33it/s]

Поиск:  56%|█████▌    | 449/800 [00:15<00:11, 29.37it/s]

Поиск:  56%|█████▋    | 452/800 [00:15<00:11, 29.01it/s]

Поиск:  57%|█████▋    | 455/800 [00:15<00:11, 28.98it/s]

Поиск:  57%|█████▋    | 458/800 [00:15<00:12, 28.24it/s]

Поиск:  58%|█████▊    | 461/800 [00:15<00:12, 27.82it/s]

Поиск:  58%|█████▊    | 464/800 [00:15<00:11, 28.36it/s]

Поиск:  58%|█████▊    | 467/800 [00:15<00:11, 28.80it/s]

Поиск:  59%|█████▉    | 470/800 [00:15<00:11, 29.11it/s]

Поиск:  59%|█████▉    | 473/800 [00:16<00:11, 28.55it/s]

Поиск:  60%|█████▉    | 477/800 [00:16<00:10, 29.89it/s]

Поиск:  60%|██████    | 481/800 [00:16<00:10, 30.70it/s]

Поиск:  61%|██████    | 485/800 [00:16<00:10, 30.14it/s]

Поиск:  61%|██████    | 489/800 [00:16<00:09, 31.13it/s]

Поиск:  62%|██████▏   | 493/800 [00:16<00:10, 29.78it/s]

Поиск:  62%|██████▏   | 497/800 [00:16<00:09, 30.46it/s]

Поиск:  63%|██████▎   | 501/800 [00:16<00:09, 30.03it/s]

Поиск:  63%|██████▎   | 505/800 [00:17<00:10, 28.89it/s]

Поиск:  64%|██████▎   | 508/800 [00:17<00:10, 28.50it/s]

Поиск:  64%|██████▍   | 511/800 [00:17<00:10, 27.51it/s]

Поиск:  64%|██████▍   | 515/800 [00:17<00:10, 28.04it/s]

Поиск:  65%|██████▍   | 518/800 [00:17<00:10, 27.58it/s]

Поиск:  65%|██████▌   | 521/800 [00:17<00:09, 27.96it/s]

Поиск:  66%|██████▌   | 524/800 [00:17<00:09, 28.34it/s]

Поиск:  66%|██████▌   | 528/800 [00:17<00:09, 29.15it/s]

Поиск:  66%|██████▋   | 532/800 [00:18<00:08, 30.26it/s]

Поиск:  67%|██████▋   | 536/800 [00:18<00:08, 29.40it/s]

Поиск:  68%|██████▊   | 540/800 [00:18<00:08, 31.05it/s]

Поиск:  68%|██████▊   | 544/800 [00:18<00:08, 30.16it/s]

Поиск:  68%|██████▊   | 548/800 [00:18<00:08, 30.55it/s]

Поиск:  69%|██████▉   | 552/800 [00:18<00:08, 30.09it/s]

Поиск:  70%|██████▉   | 556/800 [00:18<00:08, 29.30it/s]

Поиск:  70%|██████▉   | 559/800 [00:18<00:08, 28.98it/s]

Поиск:  70%|███████   | 562/800 [00:19<00:08, 28.48it/s]

Поиск:  71%|███████   | 565/800 [00:19<00:08, 28.83it/s]

Поиск:  71%|███████   | 568/800 [00:19<00:08, 28.33it/s]

Поиск:  71%|███████▏  | 571/800 [00:19<00:08, 28.49it/s]

Поиск:  72%|███████▏  | 574/800 [00:19<00:08, 27.63it/s]

Поиск:  72%|███████▏  | 578/800 [00:19<00:07, 28.20it/s]

Поиск:  73%|███████▎  | 581/800 [00:19<00:07, 27.42it/s]

Поиск:  73%|███████▎  | 584/800 [00:19<00:07, 27.85it/s]

Поиск:  74%|███████▎  | 588/800 [00:19<00:07, 29.50it/s]

Поиск:  74%|███████▍  | 592/800 [00:20<00:06, 30.47it/s]

Поиск:  74%|███████▍  | 596/800 [00:20<00:06, 29.27it/s]

Поиск:  75%|███████▍  | 599/800 [00:20<00:06, 29.43it/s]

Поиск:  75%|███████▌  | 603/800 [00:20<00:06, 30.49it/s]

Поиск:  76%|███████▌  | 607/800 [00:20<00:06, 29.89it/s]

Поиск:  76%|███████▋  | 610/800 [00:20<00:06, 28.73it/s]

Поиск:  77%|███████▋  | 614/800 [00:20<00:06, 29.49it/s]

Поиск:  77%|███████▋  | 618/800 [00:20<00:05, 30.84it/s]

Поиск:  78%|███████▊  | 622/800 [00:21<00:05, 31.16it/s]

Поиск:  78%|███████▊  | 626/800 [00:21<00:05, 31.81it/s]

Поиск:  79%|███████▉  | 630/800 [00:21<00:05, 31.17it/s]

Поиск:  79%|███████▉  | 634/800 [00:21<00:05, 30.37it/s]

Поиск:  80%|███████▉  | 638/800 [00:21<00:05, 30.03it/s]

Поиск:  80%|████████  | 642/800 [00:21<00:05, 29.84it/s]

Поиск:  81%|████████  | 645/800 [00:21<00:05, 29.43it/s]

Поиск:  81%|████████  | 648/800 [00:21<00:05, 29.28it/s]

Поиск:  82%|████████▏ | 652/800 [00:22<00:04, 30.04it/s]

Поиск:  82%|████████▏ | 656/800 [00:22<00:04, 30.65it/s]

Поиск:  82%|████████▎ | 660/800 [00:22<00:04, 30.03it/s]

Поиск:  83%|████████▎ | 664/800 [00:22<00:04, 28.77it/s]

Поиск:  84%|████████▎ | 668/800 [00:22<00:04, 28.76it/s]

Поиск:  84%|████████▍ | 672/800 [00:22<00:04, 29.35it/s]

Поиск:  84%|████████▍ | 675/800 [00:22<00:04, 29.31it/s]

Поиск:  85%|████████▍ | 678/800 [00:22<00:04, 28.75it/s]

Поиск:  85%|████████▌ | 681/800 [00:23<00:04, 28.54it/s]

Поиск:  86%|████████▌ | 684/800 [00:23<00:04, 28.48it/s]

Поиск:  86%|████████▌ | 687/800 [00:23<00:03, 28.55it/s]

Поиск:  86%|████████▋ | 690/800 [00:23<00:03, 28.18it/s]

Поиск:  87%|████████▋ | 693/800 [00:23<00:03, 28.50it/s]

Поиск:  87%|████████▋ | 696/800 [00:23<00:03, 27.69it/s]

Поиск:  87%|████████▋ | 699/800 [00:23<00:03, 27.49it/s]

Поиск:  88%|████████▊ | 702/800 [00:23<00:03, 27.91it/s]

Поиск:  88%|████████▊ | 706/800 [00:23<00:03, 28.98it/s]

Поиск:  89%|████████▉ | 710/800 [00:24<00:02, 31.85it/s]

Поиск:  89%|████████▉ | 714/800 [00:24<00:02, 34.12it/s]

Поиск:  90%|████████▉ | 718/800 [00:24<00:02, 33.00it/s]

Поиск:  90%|█████████ | 722/800 [00:24<00:02, 32.54it/s]

Поиск:  91%|█████████ | 726/800 [00:24<00:02, 30.22it/s]

Поиск:  91%|█████████▏| 730/800 [00:24<00:02, 28.52it/s]

Поиск:  92%|█████████▏| 733/800 [00:24<00:02, 27.54it/s]

Поиск:  92%|█████████▏| 736/800 [00:24<00:02, 26.74it/s]

Поиск:  92%|█████████▎| 740/800 [00:25<00:02, 28.05it/s]

Поиск:  93%|█████████▎| 743/800 [00:25<00:02, 27.27it/s]

Поиск:  93%|█████████▎| 746/800 [00:25<00:02, 26.86it/s]

Поиск:  94%|█████████▎| 749/800 [00:25<00:01, 26.66it/s]

Поиск:  94%|█████████▍| 752/800 [00:25<00:01, 27.44it/s]

Поиск:  94%|█████████▍| 755/800 [00:25<00:01, 27.04it/s]

Поиск:  95%|█████████▍| 758/800 [00:25<00:01, 26.85it/s]

Поиск:  95%|█████████▌| 761/800 [00:25<00:01, 27.25it/s]

Поиск:  96%|█████████▌| 765/800 [00:26<00:01, 28.20it/s]

Поиск:  96%|█████████▌| 768/800 [00:26<00:01, 27.52it/s]

Поиск:  96%|█████████▋| 771/800 [00:26<00:01, 27.47it/s]

Поиск:  97%|█████████▋| 775/800 [00:26<00:00, 29.33it/s]

Поиск:  97%|█████████▋| 778/800 [00:26<00:00, 28.50it/s]

Поиск:  98%|█████████▊| 782/800 [00:26<00:00, 28.77it/s]

Поиск:  98%|█████████▊| 785/800 [00:26<00:00, 28.89it/s]

Поиск:  98%|█████████▊| 788/800 [00:26<00:00, 28.95it/s]

Поиск:  99%|█████████▉| 792/800 [00:26<00:00, 30.08it/s]

Поиск: 100%|█████████▉| 796/800 [00:27<00:00, 30.27it/s]

Поиск: 100%|█████████▉| 799/800 [00:27<00:00, 29.39it/s]

2026-09-28 18:40:31,555 INFO Лучшая конфигурация geo10_cat0.7, dev Recall@50=0.8608

Поиск:   0%|          | 0/400 [00:00<?, ?it/s]

Поиск:   2%|▏         | 7/400 [00:00<00:06, 64.76it/s]

Поиск:   4%|▍         | 15/400 [00:00<00:05, 67.70it/s]

Поиск:   6%|▌         | 22/400 [00:00<00:05, 67.91it/s]

Поиск:   8%|▊         | 30/400 [00:00<00:05, 72.46it/s]

Поиск:  10%|█         | 40/400 [00:00<00:04, 78.05it/s]

Поиск:  12%|█▏        | 48/400 [00:00<00:04, 77.39it/s]

Поиск:  14%|█▍        | 56/400 [00:00<00:04, 77.28it/s]

Поиск:  16%|█▌        | 64/400 [00:00<00:04, 72.96it/s]

Поиск:  18%|█▊        | 72/400 [00:00<00:04, 71.03it/s]

Поиск:  20%|██        | 80/400 [00:01<00:04, 71.25it/s]

Поиск:  22%|██▏       | 88/400 [00:01<00:04, 66.62it/s]

Поиск:  24%|██▍       | 95/400 [00:01<00:04, 65.56it/s]

Поиск:  26%|██▌       | 102/400 [00:01<00:04, 64.62it/s]

Поиск:  27%|██▋       | 109/400 [00:01<00:04, 65.28it/s]

Поиск:  30%|██▉       | 118/400 [00:01<00:03, 70.88it/s]

Поиск:  32%|███▏      | 126/400 [00:01<00:03, 72.65it/s]

Поиск:  34%|███▎      | 134/400 [00:01<00:03, 74.50it/s]

Поиск:  36%|███▌      | 142/400 [00:02<00:03, 70.66it/s]

Поиск:  38%|███▊      | 150/400 [00:02<00:03, 69.84it/s]

Поиск:  40%|███▉      | 158/400 [00:02<00:03, 71.26it/s]

Поиск:  42%|████▏     | 166/400 [00:02<00:03, 71.63it/s]

Поиск:  44%|████▎     | 174/400 [00:02<00:03, 73.20it/s]

Поиск:  46%|████▌     | 182/400 [00:02<00:03, 72.57it/s]

Поиск:  48%|████▊     | 190/400 [00:02<00:03, 68.96it/s]

Поиск:  49%|████▉     | 197/400 [00:02<00:02, 68.90it/s]

Поиск:  51%|█████     | 204/400 [00:02<00:02, 66.45it/s]

Поиск:  53%|█████▎    | 213/400 [00:03<00:02, 72.13it/s]

Поиск:  55%|█████▌    | 221/400 [00:03<00:02, 73.78it/s]

Поиск:  57%|█████▋    | 229/400 [00:03<00:02, 68.95it/s]

Поиск:  59%|█████▉    | 237/400 [00:03<00:02, 71.34it/s]

Поиск:  61%|██████▏   | 245/400 [00:03<00:02, 70.71it/s]

Поиск:  64%|██████▍   | 255/400 [00:03<00:01, 78.66it/s]

Поиск:  66%|██████▌   | 263/400 [00:03<00:01, 76.34it/s]

Поиск:  68%|██████▊   | 271/400 [00:03<00:01, 72.57it/s]

Поиск:  70%|██████▉   | 279/400 [00:03<00:01, 70.14it/s]

Поиск:  72%|███████▏  | 287/400 [00:04<00:01, 67.47it/s]

Поиск:  74%|███████▎  | 294/400 [00:04<00:01, 65.30it/s]

Поиск:  76%|███████▌  | 303/400 [00:04<00:01, 69.37it/s]

Поиск:  78%|███████▊  | 312/400 [00:04<00:01, 72.42it/s]

Поиск:  80%|████████  | 320/400 [00:04<00:01, 70.21it/s]

Поиск:  82%|████████▏ | 328/400 [00:04<00:01, 70.52it/s]

Поиск:  84%|████████▍ | 337/400 [00:04<00:00, 73.90it/s]

Поиск:  86%|████████▋ | 346/400 [00:04<00:00, 77.06it/s]

Поиск:  88%|████████▊ | 354/400 [00:04<00:00, 76.25it/s]

Поиск:  90%|█████████ | 362/400 [00:05<00:00, 71.15it/s]

Поиск:  92%|█████████▎| 370/400 [00:05<00:00, 66.50it/s]

Поиск:  94%|█████████▍| 377/400 [00:05<00:00, 64.76it/s]

Поиск:  97%|█████████▋| 387/400 [00:05<00:00, 71.65it/s]

Поиск:  99%|█████████▉| 395/400 [00:05<00:00, 69.20it/s]

Поиск: 100%|█████████▉| 399/400 [00:05<00:00, 70.48it/s]

              dev Recall@50
geo10_cat0.7       0.860792
char0              0.854542
geo10_cat2         0.852042
geo10_cat0         0.848083
geo5_cat0.7        0.846208
no_quality         0.846208
quality_high       0.844958
geo5_cat2          0.837875
geo5_cat0          0.834750
char2              0.832042
geo2_cat0.7        0.806729
geo2_cat0          0.796937
geo2_cat2          0.775229
bm25               0.433958
text               0.416250

Выбранная конфигурация: geo10_cat0.7

          weight
title       1.50
body        1.00
char        1.00
filters     0.15
geo        10.00
microcat    0.70
quality     0.05

          holdout Recall@50
bm25               0.423750
text               0.395417
selected           0.880000

Bootstrap 95%: [0.8479166666666665, 0.91084375]

## 6. Ошибки

Показываем запросы с полным, частичным и нулевым покрытием позитивов.
Просмотр этих ошибок не меняет параметры стартового решения: конфигурация
уже выбрана на dev. Пропуск сам по себе не доказывает причину ошибки.
Для дальнейшего улучшения можно сравнить позитивные объявления и найденные
кандидаты, затем проверить семантические эмбеддинги на новой оценке.

In [12]:
display(pd.Series({
    'Все позитивы найдены': int((details.recall_at_50 == 1).sum()),
    'Часть позитивов найдена': int(details.recall_at_50.between(0, 1, inclusive='neither').sum()),
    'Нет попаданий': int((details.recall_at_50 == 0).sum()),
}).to_frame('queries'))
display(details.loc[details.recall_at_50 == 0,
                    ['search_query', 'search_location_id', 'search_infm_params_text', 'relevant_count']].head(12))

                         queries
Все позитивы найдены         350
Часть позитивов найдена        3
Нет попаданий                 47

,search_query,search_location_id,search_infm_params_text,relevant_count
10,master маникюра рязань район рязань,652460,Поиск по слотам Сегодня Поиск по слотам Завтра...,1
19,автободбор,646600,,1
25,автоинструктор по вождению на механике в путил...,637680,"Вид услуги Обучение, курсы",1
140,биохимическая завивка волос,640860,Тип услуги Услуги парикмахера Вид услуги Красо...,1
213,вынести стиральную машину,637640,Вид услуги Вывоз мусора и вторсырья,1
223,гелевые шарики,653240,"Вид услуги Праздники, мероприятия",1
252,декапирование волос,653240,Тип услуги Услуги парикмахера Вид услуги Красо...,1
258,день рождение,637640,,1
259,детейлинг автомобили,657310,,1
346,изготовление самосвальных платформ,633540,,1
351,изделия из нержавейки на заказ,653240,,1
366,капельницы на дому медсестра,639840,,1

## 7. Финальная модель

После фиксации параметров используем полный train для статистик контекста.
Из индекса удаляем объявления вне benchmark: ответ содержит только допустимые
`item_id`. Словарь и IDF сохраняются, включая влияние добавленных train-текстов.

Модель сохраняем через cloudpickle, чтобы определения классов и функций
из этого ноутбука можно было загрузить в отдельном Python-процессе без `src/`.
Затем удаляем модель из памяти и загружаем её обратно перед инференсом.

In [13]:
model.restrict_items(corpus.item_id)
model.fit_history(train, location_metadata)
assert set(model.item_ids) == set(corpus.item_id)
print('Документов в финальном индексе:', len(model.item_ids))

# Кэш — только ускорение токенизации, его содержимое не влияет на предсказания.
_STEM_CACHE.clear()
with gzip.open(MODEL_PATH, 'wb', compresslevel=3) as stream:
    cloudpickle.dump(model, stream, protocol=5)
del model
gc.collect()
with gzip.open(MODEL_PATH, 'rb') as stream:
    model = cloudpickle.load(stream)
print('Модель загружена из', MODEL_PATH)

2026-09-28 18:40:37,494 INFO Статистики контекста: 497673 обучающих пар

Документов в финальном индексе: 189212

Модель загружена из notebook_outputs/model.pkl.gz

## 8. Предсказания для benchmark и answer.csv

Запросы берём из `benchmark_queries.parquet`. Для каждого возвращаем
50 уникальных объявлений из `benchmark_items.parquet`. Проверяем точное
множество query_id, строковые идентификаторы и отсутствие лишнего CSV-индекса.
Повторно читаем записанный файл, чтобы проверить именно результат на диске.

In [14]:
"""Строгая проверка формата сдачи, включая чтение сохранённого CSV."""

import re
from pathlib import Path

import pandas as pd


def validate_submission(answer, queries, corpus_ids):
    if list(answer.columns) != ["query_id", "answer"]:
        raise ValueError("Ожидаются ровно колонки query_id,answer в таком порядке")
    expected = queries.query_id.tolist()
    if len(expected) != len(set(expected)):
        raise ValueError("Повтор query_id во входных запросах")
    if len(answer) != len(expected) or answer.query_id.duplicated().any():
        raise ValueError("Неверное число строк или повторы query_id")
    if set(answer.query_id) != set(expected):
        raise ValueError("Множество query_id не совпадает с benchmark_queries")
    corpus_ids = set(corpus_ids)
    lengths = []
    for qid, raw in answer.itertuples(index=False, name=None):
        if not isinstance(qid, str) or len(qid) != 16:
            raise ValueError(f"Неверный query_id: {qid!r}")
        if not isinstance(raw, str):
            raise ValueError("answer должен быть строкой")
        ids = raw.split(" ") if raw else []
        if not 1 <= len(ids) <= 50 or len(ids) != len(set(ids)):
            raise ValueError(f"Неверное число/повторы item_id для {qid}")
        if any(not re.fullmatch(r"[0-9a-f]{16}", i) for i in ids):
            raise ValueError(f"Неверный формат item_id для {qid}")
        if not set(ids) <= corpus_ids:
            raise ValueError(f"item_id за пределами корпуса для {qid}")
        lengths.append(len(ids))
    return {"rows": len(answer), "min_candidates": min(lengths),
            "max_candidates": max(lengths), "valid": True}


def save_submission(queries, predictions, corpus_ids, output):
    answer = pd.DataFrame({"query_id": queries.query_id,
                           "answer": [" ".join(ids) for ids in predictions]})
    validate_submission(answer, queries, corpus_ids)
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    answer.to_csv(output, index=False, encoding="utf-8", lineterminator="\n")
    reread = pd.read_csv(output, dtype=str, keep_default_na=False)
    return validate_submission(reread, queries, corpus_ids)

In [15]:
predictions = model.predict(queries)
checks = save_submission(queries, predictions, corpus.item_id, ANSWER_PATH)
answer = pd.read_csv(ANSWER_PATH, dtype=str, keep_default_na=False)
answer_hash = hashlib.sha256(ANSWER_PATH.read_bytes()).hexdigest()
manifest = {
    'seed': SEED,
    'config': model.config.as_dict(),
    'corpus_size': len(corpus),
    'query_count': len(queries),
    'submission_checks': checks,
    'answer_sha256': answer_hash,
    'elapsed_seconds': round(time.perf_counter() - started, 2),
}
(REPORT_DIR / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2))
print('Проверка:', checks)
print('SHA256:', answer_hash)
print('Файл для отправки:', ANSWER_PATH.resolve())
if previous_answer_hash:
    print('Совпадает с ранее сохранённым answer.csv:', answer_hash == previous_answer_hash)
display(answer.head())

Поиск:   0%|          | 0/2452 [00:00<?, ?it/s]

Поиск:   0%|          | 8/2452 [00:00<00:32, 75.83it/s]

Поиск:   1%|          | 19/2452 [00:00<00:27, 89.68it/s]

Поиск:   1%|          | 30/2452 [00:00<00:25, 93.59it/s]

Поиск:   2%|▏         | 41/2452 [00:00<00:25, 95.49it/s]

Поиск:   2%|▏         | 51/2452 [00:00<00:26, 89.91it/s]

Поиск:   2%|▏         | 61/2452 [00:00<00:26, 91.32it/s]

Поиск:   3%|▎         | 72/2452 [00:00<00:24, 95.98it/s]

Поиск:   3%|▎         | 82/2452 [00:00<00:24, 95.16it/s]

Поиск:   4%|▍         | 94/2452 [00:00<00:23, 99.89it/s]

Поиск:   4%|▍         | 105/2452 [00:01<00:24, 94.79it/s]

Поиск:   5%|▍         | 115/2452 [00:01<00:25, 92.07it/s]

Поиск:   5%|▌         | 126/2452 [00:01<00:24, 96.56it/s]

Поиск:   6%|▌         | 136/2452 [00:01<00:24, 95.29it/s]

Поиск:   6%|▌         | 146/2452 [00:01<00:25, 91.62it/s]

Поиск:   6%|▋         | 156/2452 [00:01<00:25, 89.78it/s]

Поиск:   7%|▋         | 166/2452 [00:01<00:26, 86.99it/s]

Поиск:   7%|▋         | 177/2452 [00:01<00:24, 92.52it/s]

Поиск:   8%|▊         | 189/2452 [00:02<00:23, 96.95it/s]

Поиск:   8%|▊         | 199/2452 [00:02<00:24, 90.53it/s]

Поиск:   9%|▊         | 209/2452 [00:02<00:24, 90.08it/s]

Поиск:   9%|▉         | 221/2452 [00:02<00:23, 96.66it/s]

Поиск:  10%|▉         | 233/2452 [00:02<00:21, 101.98it/s]

Поиск:  10%|▉         | 244/2452 [00:02<00:23, 94.38it/s]

Поиск:  10%|█         | 254/2452 [00:02<00:23, 92.84it/s]

Поиск:  11%|█         | 264/2452 [00:02<00:23, 91.44it/s]

Поиск:  11%|█         | 275/2452 [00:02<00:22, 95.44it/s]

Поиск:  12%|█▏        | 285/2452 [00:03<00:23, 90.66it/s]

Поиск:  12%|█▏        | 295/2452 [00:03<00:24, 88.21it/s]

Поиск:  12%|█▏        | 304/2452 [00:03<00:24, 85.99it/s]

Поиск:  13%|█▎        | 318/2452 [00:03<00:21, 99.88it/s]

Поиск:  13%|█▎        | 329/2452 [00:03<00:20, 101.84it/s]

Поиск:  14%|█▍        | 340/2452 [00:03<00:22, 95.80it/s]

Поиск:  14%|█▍        | 350/2452 [00:03<00:23, 88.18it/s]

Поиск:  15%|█▍        | 361/2452 [00:03<00:22, 93.24it/s]

Поиск:  15%|█▌        | 376/2452 [00:03<00:19, 108.00it/s]

Поиск:  16%|█▌        | 388/2452 [00:04<00:20, 100.97it/s]

Поиск:  16%|█▋        | 399/2452 [00:04<00:22, 93.27it/s]

Поиск:  17%|█▋        | 411/2452 [00:04<00:21, 96.89it/s]

Поиск:  17%|█▋        | 423/2452 [00:04<00:20, 101.38it/s]

Поиск:  18%|█▊        | 434/2452 [00:04<00:21, 92.49it/s]

Поиск:  18%|█▊        | 447/2452 [00:04<00:19, 101.54it/s]

Поиск:  19%|█▊        | 459/2452 [00:04<00:19, 103.96it/s]

Поиск:  19%|█▉        | 471/2452 [00:04<00:18, 108.12it/s]

Поиск:  20%|█▉        | 483/2452 [00:05<00:20, 97.38it/s]

Поиск:  20%|██        | 494/2452 [00:05<00:19, 98.43it/s]

Поиск:  21%|██        | 505/2452 [00:05<00:19, 98.90it/s]

Поиск:  21%|██        | 517/2452 [00:05<00:19, 101.80it/s]

Поиск:  22%|██▏       | 528/2452 [00:05<00:18, 102.77it/s]

Поиск:  22%|██▏       | 539/2452 [00:05<00:18, 103.09it/s]

Поиск:  22%|██▏       | 550/2452 [00:05<00:19, 99.02it/s]

Поиск:  23%|██▎       | 561/2452 [00:05<00:18, 101.39it/s]

Поиск:  23%|██▎       | 572/2452 [00:05<00:18, 99.22it/s]

Поиск:  24%|██▍       | 583/2452 [00:06<00:18, 102.09it/s]

Поиск:  24%|██▍       | 594/2452 [00:06<00:17, 104.11it/s]

Поиск:  25%|██▍       | 605/2452 [00:06<00:18, 98.70it/s]

Поиск:  25%|██▌       | 617/2452 [00:06<00:18, 101.72it/s]

Поиск:  26%|██▌       | 628/2452 [00:06<00:19, 93.34it/s]

Поиск:  26%|██▌       | 638/2452 [00:06<00:19, 93.75it/s]

Поиск:  26%|██▋       | 648/2452 [00:06<00:19, 94.54it/s]

Поиск:  27%|██▋       | 658/2452 [00:06<00:19, 92.41it/s]

Поиск:  27%|██▋       | 670/2452 [00:06<00:17, 99.83it/s]

Поиск:  28%|██▊       | 681/2452 [00:07<00:17, 101.53it/s]

Поиск:  28%|██▊       | 692/2452 [00:07<00:17, 100.01it/s]

Поиск:  29%|██▊       | 703/2452 [00:07<00:17, 101.95it/s]

Поиск:  29%|██▉       | 714/2452 [00:07<00:17, 97.83it/s]

Поиск:  30%|██▉       | 724/2452 [00:07<00:17, 97.89it/s]

Поиск:  30%|███       | 736/2452 [00:07<00:16, 101.16it/s]

Поиск:  30%|███       | 747/2452 [00:07<00:17, 99.52it/s]

Поиск:  31%|███       | 757/2452 [00:07<00:17, 94.78it/s]

Поиск:  31%|███▏      | 767/2452 [00:07<00:18, 93.30it/s]

Поиск:  32%|███▏      | 779/2452 [00:08<00:16, 99.46it/s]

Поиск:  32%|███▏      | 789/2452 [00:08<00:17, 97.25it/s]

Поиск:  33%|███▎      | 799/2452 [00:08<00:17, 92.65it/s]

Поиск:  33%|███▎      | 811/2452 [00:08<00:16, 99.46it/s]

Поиск:  34%|███▎      | 822/2452 [00:08<00:15, 102.00it/s]

Поиск:  34%|███▍      | 837/2452 [00:08<00:14, 112.08it/s]

Поиск:  35%|███▍      | 849/2452 [00:08<00:16, 100.04it/s]

Поиск:  35%|███▌      | 860/2452 [00:08<00:15, 102.34it/s]

Поиск:  36%|███▌      | 871/2452 [00:08<00:15, 102.46it/s]

Поиск:  36%|███▌      | 882/2452 [00:09<00:16, 95.48it/s]

Поиск:  36%|███▋      | 892/2452 [00:09<00:16, 93.37it/s]

Поиск:  37%|███▋      | 902/2452 [00:09<00:16, 91.92it/s]

Поиск:  37%|███▋      | 912/2452 [00:09<00:17, 89.86it/s]

Поиск:  38%|███▊      | 922/2452 [00:09<00:16, 91.41it/s]

Поиск:  38%|███▊      | 933/2452 [00:09<00:16, 94.67it/s]

Поиск:  38%|███▊      | 943/2452 [00:09<00:15, 95.73it/s]

Поиск:  39%|███▉      | 959/2452 [00:09<00:13, 110.88it/s]

Поиск:  40%|███▉      | 971/2452 [00:09<00:13, 108.30it/s]

Поиск:  40%|████      | 982/2452 [00:10<00:14, 100.51it/s]

Поиск:  40%|████      | 993/2452 [00:10<00:15, 96.64it/s]

Поиск:  41%|████      | 1003/2452 [00:10<00:15, 92.61it/s]

Поиск:  41%|████▏     | 1013/2452 [00:10<00:15, 91.07it/s]

Поиск:  42%|████▏     | 1024/2452 [00:10<00:14, 95.33it/s]

Поиск:  42%|████▏     | 1034/2452 [00:10<00:15, 94.02it/s]

Поиск:  43%|████▎     | 1044/2452 [00:10<00:15, 89.89it/s]

Поиск:  43%|████▎     | 1054/2452 [00:10<00:15, 87.48it/s]

Поиск:  44%|████▎     | 1067/2452 [00:11<00:14, 97.54it/s]

Поиск:  44%|████▍     | 1077/2452 [00:11<00:15, 91.25it/s]

Поиск:  44%|████▍     | 1087/2452 [00:11<00:14, 93.01it/s]

Поиск:  45%|████▍     | 1098/2452 [00:11<00:13, 97.43it/s]

Поиск:  45%|████▌     | 1110/2452 [00:11<00:13, 100.41it/s]

Поиск:  46%|████▌     | 1121/2452 [00:11<00:13, 99.28it/s]

Поиск:  46%|████▌     | 1131/2452 [00:11<00:13, 97.21it/s]

Поиск:  47%|████▋     | 1143/2452 [00:11<00:12, 103.01it/s]

Поиск:  47%|████▋     | 1154/2452 [00:11<00:13, 97.45it/s]

Поиск:  48%|████▊     | 1165/2452 [00:12<00:13, 98.10it/s]

Поиск:  48%|████▊     | 1176/2452 [00:12<00:12, 100.95it/s]

Поиск:  48%|████▊     | 1187/2452 [00:12<00:12, 103.47it/s]

Поиск:  49%|████▉     | 1198/2452 [00:12<00:12, 100.03it/s]

Поиск:  49%|████▉     | 1209/2452 [00:12<00:12, 98.16it/s]

Поиск:  50%|████▉     | 1224/2452 [00:12<00:11, 109.15it/s]

Поиск:  50%|█████     | 1236/2452 [00:12<00:10, 110.93it/s]

Поиск:  51%|█████     | 1248/2452 [00:12<00:12, 99.36it/s]

Поиск:  51%|█████▏    | 1260/2452 [00:12<00:11, 101.14it/s]

Поиск:  52%|█████▏    | 1274/2452 [00:13<00:10, 107.82it/s]

Поиск:  52%|█████▏    | 1286/2452 [00:13<00:10, 108.03it/s]

Поиск:  53%|█████▎    | 1297/2452 [00:13<00:11, 99.50it/s]

Поиск:  53%|█████▎    | 1308/2452 [00:13<00:12, 93.02it/s]

Поиск:  54%|█████▍    | 1320/2452 [00:13<00:11, 96.54it/s]

Поиск:  54%|█████▍    | 1330/2452 [00:13<00:11, 95.21it/s]

Поиск:  55%|█████▍    | 1340/2452 [00:13<00:12, 90.14it/s]

Поиск:  55%|█████▌    | 1352/2452 [00:13<00:11, 94.81it/s]

Поиск:  56%|█████▌    | 1365/2452 [00:14<00:10, 101.99it/s]

Поиск:  56%|█████▌    | 1377/2452 [00:14<00:10, 105.70it/s]

Поиск:  57%|█████▋    | 1390/2452 [00:14<00:09, 109.34it/s]

Поиск:  57%|█████▋    | 1402/2452 [00:14<00:10, 96.21it/s]

Поиск:  58%|█████▊    | 1414/2452 [00:14<00:10, 99.25it/s]

Поиск:  58%|█████▊    | 1425/2452 [00:14<00:10, 98.10it/s]

Поиск:  59%|█████▊    | 1435/2452 [00:14<00:10, 95.86it/s]

Поиск:  59%|█████▉    | 1445/2452 [00:14<00:11, 89.57it/s]

Поиск:  59%|█████▉    | 1456/2452 [00:14<00:10, 92.60it/s]

Поиск:  60%|█████▉    | 1468/2452 [00:15<00:09, 99.55it/s]

Поиск:  60%|██████    | 1479/2452 [00:15<00:09, 97.69it/s]

Поиск:  61%|██████    | 1489/2452 [00:15<00:10, 93.07it/s]

Поиск:  61%|██████    | 1499/2452 [00:15<00:10, 89.38it/s]

Поиск:  62%|██████▏   | 1509/2452 [00:15<00:10, 90.16it/s]

Поиск:  62%|██████▏   | 1521/2452 [00:15<00:09, 97.82it/s]

Поиск:  63%|██████▎   | 1534/2452 [00:15<00:08, 106.58it/s]

Поиск:  63%|██████▎   | 1545/2452 [00:15<00:09, 98.41it/s]

Поиск:  63%|██████▎   | 1556/2452 [00:16<00:09, 96.56it/s]

Поиск:  64%|██████▍   | 1568/2452 [00:16<00:08, 100.17it/s]

Поиск:  64%|██████▍   | 1580/2452 [00:16<00:08, 104.69it/s]

Поиск:  65%|██████▌   | 1594/2452 [00:16<00:07, 113.59it/s]

Поиск:  65%|██████▌   | 1606/2452 [00:16<00:08, 99.31it/s]

Поиск:  66%|██████▌   | 1618/2452 [00:16<00:08, 101.73it/s]

Поиск:  66%|██████▋   | 1629/2452 [00:16<00:08, 99.64it/s]

Поиск:  67%|██████▋   | 1640/2452 [00:16<00:08, 99.05it/s]

Поиск:  67%|██████▋   | 1651/2452 [00:16<00:08, 95.71it/s]

Поиск:  68%|██████▊   | 1661/2452 [00:17<00:08, 95.04it/s]

Поиск:  68%|██████▊   | 1673/2452 [00:17<00:07, 100.54it/s]

Поиск:  69%|██████▊   | 1685/2452 [00:17<00:07, 103.45it/s]

Поиск:  69%|██████▉   | 1696/2452 [00:17<00:07, 103.07it/s]

Поиск:  70%|██████▉   | 1707/2452 [00:17<00:07, 98.77it/s]

Поиск:  70%|███████   | 1717/2452 [00:17<00:07, 95.06it/s]

Поиск:  70%|███████   | 1727/2452 [00:17<00:07, 96.35it/s]

Поиск:  71%|███████   | 1737/2452 [00:17<00:07, 95.49it/s]

Поиск:  71%|███████   | 1747/2452 [00:17<00:07, 92.10it/s]

Поиск:  72%|███████▏  | 1757/2452 [00:18<00:07, 90.84it/s]

Поиск:  72%|███████▏  | 1767/2452 [00:18<00:07, 92.57it/s]

Поиск:  73%|███████▎  | 1778/2452 [00:18<00:06, 96.93it/s]

Поиск:  73%|███████▎  | 1789/2452 [00:18<00:06, 100.37it/s]

Поиск:  73%|███████▎  | 1800/2452 [00:18<00:07, 91.26it/s]

Поиск:  74%|███████▍  | 1810/2452 [00:18<00:07, 87.51it/s]

Поиск:  74%|███████▍  | 1826/2452 [00:18<00:06, 103.96it/s]

Поиск:  75%|███████▍  | 1838/2452 [00:18<00:05, 106.17it/s]

Поиск:  75%|███████▌  | 1849/2452 [00:18<00:06, 94.98it/s]

Поиск:  76%|███████▌  | 1859/2452 [00:19<00:06, 94.49it/s]

Поиск:  76%|███████▋  | 1871/2452 [00:19<00:05, 100.41it/s]

Поиск:  77%|███████▋  | 1885/2452 [00:19<00:05, 107.15it/s]

Поиск:  77%|███████▋  | 1897/2452 [00:19<00:05, 108.55it/s]

Поиск:  78%|███████▊  | 1908/2452 [00:19<00:05, 99.09it/s]

Поиск:  78%|███████▊  | 1919/2452 [00:19<00:05, 95.83it/s]

Поиск:  79%|███████▊  | 1930/2452 [00:19<00:05, 96.80it/s]

Поиск:  79%|███████▉  | 1942/2452 [00:19<00:04, 102.85it/s]

Поиск:  80%|███████▉  | 1953/2452 [00:20<00:05, 99.04it/s]

Поиск:  80%|████████  | 1965/2452 [00:20<00:04, 104.72it/s]

Поиск:  81%|████████  | 1976/2452 [00:20<00:04, 99.70it/s]

Поиск:  81%|████████  | 1989/2452 [00:20<00:04, 107.62it/s]

Поиск:  82%|████████▏ | 2002/2452 [00:20<00:04, 111.17it/s]

Поиск:  82%|████████▏ | 2014/2452 [00:20<00:03, 112.19it/s]

Поиск:  83%|████████▎ | 2026/2452 [00:20<00:04, 100.64it/s]

Поиск:  83%|████████▎ | 2037/2452 [00:20<00:04, 100.78it/s]

Поиск:  84%|████████▎ | 2048/2452 [00:20<00:03, 101.27it/s]

Поиск:  84%|████████▍ | 2060/2452 [00:21<00:03, 105.22it/s]

Поиск:  84%|████████▍ | 2071/2452 [00:21<00:03, 102.22it/s]

Поиск:  85%|████████▍ | 2082/2452 [00:21<00:03, 101.41it/s]

Поиск:  85%|████████▌ | 2093/2452 [00:21<00:03, 103.20it/s]

Поиск:  86%|████████▌ | 2105/2452 [00:21<00:03, 107.60it/s]

Поиск:  86%|████████▋ | 2116/2452 [00:21<00:03, 101.79it/s]

Поиск:  87%|████████▋ | 2127/2452 [00:21<00:03, 95.33it/s]

Поиск:  87%|████████▋ | 2139/2452 [00:21<00:03, 101.58it/s]

Поиск:  88%|████████▊ | 2150/2452 [00:21<00:02, 101.54it/s]

Поиск:  88%|████████▊ | 2161/2452 [00:22<00:02, 97.75it/s]

Поиск:  89%|████████▊ | 2171/2452 [00:22<00:03, 93.41it/s]

Поиск:  89%|████████▉ | 2181/2452 [00:22<00:02, 93.94it/s]

Поиск:  89%|████████▉ | 2193/2452 [00:22<00:02, 100.91it/s]

Поиск:  90%|████████▉ | 2204/2452 [00:22<00:02, 93.99it/s]

Поиск:  90%|█████████ | 2214/2452 [00:22<00:02, 94.83it/s]

Поиск:  91%|█████████ | 2224/2452 [00:22<00:02, 87.58it/s]

Поиск:  91%|█████████ | 2234/2452 [00:22<00:02, 88.40it/s]

Поиск:  92%|█████████▏| 2244/2452 [00:22<00:02, 91.41it/s]

Поиск:  92%|█████████▏| 2255/2452 [00:23<00:02, 93.85it/s]

Поиск:  92%|█████████▏| 2265/2452 [00:23<00:02, 90.48it/s]

Поиск:  93%|█████████▎| 2276/2452 [00:23<00:01, 95.00it/s]

Поиск:  93%|█████████▎| 2286/2452 [00:23<00:01, 95.35it/s]

Поиск:  94%|█████████▎| 2297/2452 [00:23<00:01, 97.02it/s]

Поиск:  94%|█████████▍| 2307/2452 [00:23<00:01, 94.34it/s]

Поиск:  94%|█████████▍| 2317/2452 [00:23<00:01, 89.53it/s]

Поиск:  95%|█████████▍| 2327/2452 [00:23<00:01, 87.08it/s]

Поиск:  95%|█████████▌| 2337/2452 [00:23<00:01, 88.43it/s]

Поиск:  96%|█████████▌| 2347/2452 [00:24<00:01, 90.37it/s]

Поиск:  96%|█████████▌| 2357/2452 [00:24<00:01, 86.86it/s]

Поиск:  97%|█████████▋| 2369/2452 [00:24<00:00, 94.45it/s]

Поиск:  97%|█████████▋| 2380/2452 [00:24<00:00, 98.20it/s]

Поиск:  98%|█████████▊| 2392/2452 [00:24<00:00, 103.94it/s]

Поиск:  98%|█████████▊| 2403/2452 [00:24<00:00, 97.77it/s]

Поиск:  99%|█████████▊| 2416/2452 [00:24<00:00, 106.33it/s]

Поиск:  99%|█████████▉| 2427/2452 [00:24<00:00, 103.00it/s]

Поиск:  99%|█████████▉| 2438/2452 [00:24<00:00, 98.59it/s]

Поиск: 100%|█████████▉| 2448/2452 [00:25<00:00, 97.73it/s]

Поиск: 100%|██████████| 2452/2452 [00:25<00:00, 97.66it/s]

Проверка: {'rows': 2452, 'min_candidates': 50, 'max_candidates': 50, 'valid': True}
SHA256: d93acf026e711a66704764a229785fc3b6fad738963364c2ddb22396d8408d69
Файл для отправки: /private/tmp/avito-notebook-check-sm6j76i3/answer.csv

           query_id                                             answer
0  70DfDUpwjxB4lzFd  b92ee8f432cec2d1 255fbeaf526a1cc1 355392014208...
1  JTrdTaZJvSiLPkXj  422d3ffdd5bbf626 cbeccbecb1fb8d86 1c6d2079e07f...
2  LZCZNoVG4AFUkVRJ  dab52187b4500d9b 3f89b8062dc85f1c d8fce513e4f0...
3  660ac9QVtXkRxZC3  4c15e7abba063ac5 af91ec4a29b66636 1e5924dc546b...
4  YgHcM9MVbxKnxD1e  1a62634394544781 9c41fe789f98d702 53f9c8caeeb8...

## 9. Повторный инференс и использованные инструменты

Для последующего инференса достаточно сохранённого `notebook_outputs/model.pkl.gz`,
benchmark-запросов и установленных библиотек. Код классов включён в артефакт:

```python
import gzip, cloudpickle, pandas as pd
with gzip.open('notebook_outputs/model.pkl.gz', 'rb') as stream:
    model = cloudpickle.load(stream)
queries = pd.read_parquet('datasets/benchmark_queries.parquet')
predictions = model.predict(queries)
pd.DataFrame({
    'query_id': queries['query_id'],
    'answer': [' '.join(ids) for ids in predictions],
}).to_csv('answer.csv', index=False)
```

Использованы классический BM25 (собственная разреженная реализация),
[scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html),
[NLTK Snowball](https://www.nltk.org/api/nltk.stem.snowball.html), SciPy, NumPy,
pandas, PyArrow, tqdm и cloudpickle. Предобученных нейросетей в этой версии нет.
Параметры, локальные метрики и контрольная сумма CSV сохраняются вместе
с результатами. Скрытая метрика станет известна только после отправки файла.